name: Deploy ENS

on:
  workflow_dispatch:
    inputs:
      IPFS_CID:
        description: 'IPFS CID'
        required: true
        type: string
      CHAIN_NAME:
        description: 'Chain name'
        required: true
        type: choice
        options:
          - goerli
          - mainnet

jobs:
  ens-deploy:
    uses: lidofinance/actions/.github/workflows/ci-ens.yml@main
    with:
      ipfs_cid: ${{ inputs.IPFS_CID }}
      chain_name: ${{ inputs.CHAIN_NAME }}
    secrets:
      DELEGATE_PRIVATE_KEY: ${{ secrets.DELEGATE_PRIVATE_KEY }}
