name: IPFS testnet

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  ipfs_folder: 'out'
jobs:
  prepare-for-ipfs:
    runs-on: ubuntu-latest
    environment: IPFS Testnet
    outputs:
      ipfs_folder: ${{ env.ipfs_folder }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          fetch-tags: true
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Build
        run: |
          yarn build-ipfs
        env:
          DEFAULT_CHAIN: ${{ vars.DEFAULT_CHAIN }}
          SUPPORTED_CHAINS: ${{ vars.SUPPORTED_CHAINS }}
          WIDGET_API_BASE_PATH_FOR_IPFS: ${{ vars.WIDGET_API_BASE_PATH_FOR_IPFS }}
          REWARDS_BACKEND_BASE_PATH: ${{ vars.REWARDS_BACKEND_BASE_PATH }}
          WQ_API_BASE_PATH: ${{ vars.WQ_API_BASE_PATH }}
          ETH_API_BASE_PATH: ${{ vars.ETH_API_BASE_PATH }}
          PREFILL_UNSAFE_EL_RPC_URLS: ${{ secrets.PREFILL_UNSAFE_EL_RPC_URLS }}
          WALLETCONNECT_PROJECT_ID: ${{ secrets.WALLETCONNECT_PROJECT_ID }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ipfs_folder }}
          path: ${{ env.ipfs_folder }}
          retention-days: 1
  ipfs-pinning:
    needs: prepare-for-ipfs
    uses: lidofinance/actions/.github/workflows/ci-ipfs.yml@main
    with:
      ipfs_folder: ${{ needs.prepare-for-ipfs.outputs.ipfs_folder }}
      current_branch: ${{ github.ref_name }}
      IS_CREATE_RELEASE: false
    secrets:
      W3S_TOKEN: ${{ secrets.W3S_TOKEN }}
      GW3_TOKEN: ''
